config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :players do
        resources :aktions, only: [:index, :show]        
      end
    end
  end

  resources :friendships
  resources :accepted_challenges
  resources :challenges
  resources :interruptions
  resources :insights
  resources :aktions do
    collection { get :continue, :start, :test, :current }
  end
  resources :role_assignments
  resources :project_memberships
  resources :team_memberships do
    member { get :update_from_api }
  end
  resources :locations, :verbs
  resources :players do
    resources :aktions
  end
  resources :teams do
    member { get :join, :leave }
    resources :projects
    resources :roles
  end

  resources :roles
  resources :projects

  root to: 'visitors#welcome'
  get '/contact' => 'visitors#contact'
  get '/welcome' => 'visitors#welcome'
  get '/help' => 'visitors#help'
  get '/chat' => 'visitors#chat'
  get '/sounds' => 'visitors#sounds'
  get '/scores' => 'visitors#scores'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/accepted_challenge.rb
class AcceptedChallenge < ActiveRecord::Base
  belongs_to :challenge
  belongs_to :player

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  
  def description
    challenge.description rescue 'Challenge Not Found'
  end
  
  def item_type
    challenge.try(:item_type)
  end

  def greater_than
    challenge.try(:greater_than)
  end

  def also_accepted_by
    other_accepted_challenges = challenge.accepted_challenges - [self]
    other_accepted_challenges.map{ |ac| ac.player }.compact
  end
end

app/controllers/accepted_challenges_controller.rb
class AcceptedChallengesController < ApplicationController
  before_action :set_accepted_challenge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_player!

  def index
    @player = Player.find_by_id(params[:player_id]) || current_player
    @accepted_challenges = @player.accepted_challenges
  end

  def show
  end

  def new
    AcceptedChallenge.create!(challenge_id: params[:challenge_id], player_id: params[:player_id], active: params[:active])
    redirect_to back_or(accepted_challenges_url), notice: 'You have accepted this challenge.'
  end

  def edit
  end

  def update
    respond_to do |format|
      if @accepted_challenge.update(accepted_challenge_params)
        format.html { redirect_to accepted_challenges_url, notice: 'Accepted challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @accepted_challenge }
      else
        format.html { render :edit }
        format.json { render json: @accepted_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @accepted_challenge.destroy
    respond_to do |format|
      format.html { redirect_to accepted_challenges_url, notice: 'Accepted challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_accepted_challenge
      @accepted_challenge = AcceptedChallenge.find(params[:id])
    end

    def accepted_challenge_params
      params.require(:accepted_challenge).permit(:player_id, :challenge_id, :active, :comments, :starting, :ending)
    end
end

app/helpers/accepted_challenges_helper.rb
module AcceptedChallengesHelper
end

app/views/accepted_challenges/_accepted_challenge.html.haml
.today-summary.challenge{"style" => "#{(1..4).include?(item_type) ? 'margin-left: 15px; width: 108px;' : ''}"}
  - ac = item_challenges.try(:first)
  - count = Challenge.count(current_player, item_type)
  - if count > 0 || ac || item_type == 0 || item_type == 2
    .challenge-count.text-right= count
    .challenge-item= Challenge::TYPES.to_h.invert[item_type]
    - if ac
      - out_of = ac.greater_than
      - t = "See this accepted challenge and more. #{ac.challenge.comments}"
      - if count >= out_of
        .challenge-goal.green-text= link_to "/#{out_of}", accepted_challenges_path, title: t
      - elsif count >= (out_of / 2)
        .challenge-goal.yellow-text= link_to "/#{out_of}", accepted_challenges_path, title: t
      - else
        .challenge-goal.reddish-text= link_to "/#{out_of}", accepted_challenges_path, title: t

app/views/accepted_challenges/_form.html.haml
= simple_form_for(@accepted_challenge) do |f|
  = f.error_notification

  .form-inputs
    .large-3.medium-3.small-6= f.association :player
    .large-6.medium-3.small-6= f.association :challenge, label_method: :description
    .large-3.medium-3.small-6= f.input :comments
    = f.input :active
    %hr

  .form-actions
    = f.button :submit

app/views/accepted_challenges/edit.html.haml
%h1 Editing accepted_challenge

= render 'form'

= link_to 'Show', @accepted_challenge
\|
= link_to 'Back', accepted_challenges_path

app/views/accepted_challenges/index.html.haml
%h1 My Accepted Challenges

%p When you first join TheActionGame.com you get auto-assigned two random challenges.
You can remove them and add others from this page.

%table
  %thead
    %tr
      %th
      %th Challenge
      %th Today?
      %th Also Accepted By      
      %th Challenge Comments
      - if current_player.admin?
        %th.review-bg Who
        %th Active

  %tbody
    - @accepted_challenges.each do |ac|
      %tr
        %td.green-text= link_to 'Remove', ac, :method => :delete, :data => { :confirm => 'Are you sure?' }
        - if current_player.admin?
          %td= link_to ac.description, edit_challenge_path(ac.challenge) rescue 'Challenge Missing'
        - else
          %td= ac.description rescue 'Challenge Missing'
        %td
          - actual = Challenge.count(@player, ac.item_type)
          - if actual >= ac.greater_than
            .green-text= '✔︎ ' + actual.to_s
          - else
            .red-text= '✘ ' + actual.to_s
        %td= ac.also_accepted_by.map(&:first_name).join(', ')
        %td= ac.challenge.comments rescue 'Missing'
        - if current_player.admin?
          %td.review-bg= ac.player.first_name rescue 'Missing Name'
          %td= ac.active rescue 'Missing'

%br

.button.white-text= link_to 'Accept Another Challenge!', challenges_path

app/views/accepted_challenges/new.html.haml
%h1 New accepted_challenge

= render 'form'

= link_to 'Back', accepted_challenges_path

app/views/accepted_challenges/show.html.haml
%p#notice= notice

%p
  %b Player:
  = @accepted_challenge.player_id
%p
  %b Challenge:
  = @accepted_challenge.challenge_id
%p
  %b Active:
  = @accepted_challenge.active
%p
  %b Comments:
  = @accepted_challenge.comments

= link_to 'Edit', edit_accepted_challenge_path(@accepted_challenge)
\|
= link_to 'Back', accepted_challenges_path