config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :players do
        resources :aktions, only: [:index, :show]        
      end
    end
  end

  resources :friendships
  resources :accepted_challenges
  resources :challenges
  resources :interruptions
  resources :insights
  resources :aktions do
    collection { get :continue, :start, :test, :current }
  end
  resources :role_assignments
  resources :project_memberships
  resources :team_memberships do
    member { get :update_from_api }
  end
  resources :locations, :verbs
  resources :players do
    resources :aktions
  end
  resources :teams do
    member { get :join, :leave }
    resources :projects
    resources :roles
  end

  resources :roles
  resources :projects

  root to: 'visitors#welcome'
  get '/contact' => 'visitors#contact'
  get '/welcome' => 'visitors#welcome'
  get '/help' => 'visitors#help'
  get '/chat' => 'visitors#chat'
  get '/sounds' => 'visitors#sounds'
  get '/scores' => 'visitors#scores'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :team
  belongs_to :parent, class_name: 'Project'
  has_many :children, class_name: 'Project', foreign_key: 'parent_id'
  has_many :aktions
  has_many :project_memberships
  has_many :players, through: :project_memberships
  belongs_to :creator, class_name: 'Project'

  def self.search(tm, playa)
    tm.projects.select{ |p| playa.committed_to(p) }
  end

  def self.initialize_for(solo_team, playa)
    return 'Already initialized' if solo_team.projects.first
    p1 = Project.create!(team_id: solo_team.id, name: 'Recurring/Maintenance', commitment: true)
    p2 = Project.create!(team_id: solo_team.id, name: 'I know how to use TheActionGame.com', commitment: false)
    playa.projects << p1
    playa.projects << p2
  end
  
  def team_project
    "#{team.name}: #{name}"
  end

  def short_team_project
    "#{team_id? ? team.short_safe : 'N/A'}/#{name}"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_team, except: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
    @project.active = true
    @project.commitment = true
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.team_id = params[:team_id] unless @project.team_id
    @project.active = params[:active] if @project.active.nil?
    @project.commitment = params[:commitment] if @project.commitment.nil?

    if @project.save
      render json: @project
      if @project.creator_id
        ProjectMembership.create!(project_id: @project.id, player_id: @project.creator_id, active: true)
      end
    else
      render json: @project.errors, status: :unprocessable_entity
    end
    #
    # respond_to do |format|
    #   if @project.save
    #     format.html { redirect_to @project.team || projects_path, notice: 'Project was successfully created.' }
    #     format.json { render :show, status: :created, location: @project }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @project.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project.team || projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def set_team
      @team = Team.find_by_id(params[:team_id])
    end

    def project_params
      params.require(:project).permit(:name, :team_id, :active, :commitment, :visible_to, :ancestry,
        :description, :parent_id, :creator_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification
  
  .form-inputs
    .large-4.medium-6.small-12.columns= f.input :name, autofocus: true
    .large-4.medium-6.small-12.columns= f.association :parent, label: 'Parent Project'
    .large-4.medium-6.small-12.columns= f.input :visible_to
    .large-4.medium-6.small-12.columns
      = f.input :active
      = f.input :commitment
    .large-4.medium-6.small-12.columns
  %hr
  .form-actions
    .large-4.medium-6.small-12.columns= f.button :submit
    .large-4.medium-6.small-12.columns= f.association :team, include_blank: true
    .large-4.medium-6.small-12.columns
  %hr

app/views/projects/_project.html.haml
%tr.stripe
  - if current_player.committed_to(project)
    %td.blue-text COMMITTED
  - else
    %td.green-text= link_to 'TAKE ON', new_project_membership_path(project_id: project.id, player_id: current_player.id), remote: true
  / %td= link_to 'Edit', edit_project_path(project)
  %td= link_to project.team.short_safe, project.team if project.team
  %td= link_to project.name, project
  %td= project.active
  %td= project.commitment
  %td= project.aktions.count
  %td= project.created_at.strftime('%b-%d')
  %td= project.updated_at.strftime('%b-%d')
  %td= project.description

app/views/projects/_projects.html.haml
%h5
  Projects
  - if team
    = link_to "(New for #{team.name})", new_team_project_path(team)
  - else
    = link_to "(New)", new_project_path

.large-12.medium-12.small-12.columns
  %table#projects-table.compact
    %thead
      %th
      %th Tm
      %th Name
      %th Active
      %th Commitment
      %th Actions
      %th Created
      %th Updated
      %th Description
    %tbody
      = render projects

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h4
  Projects
  = link_to "(new)", new_project_path

= render 'projects', projects: @projects, team: nil

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p
  %b Name:
  = @project.name
%p
  %b Team:
  = @project.team_id
%p
  %b Active:
  = @project.active
%p
  %b Commitment:
  = @project.commitment
%p
  %b Visible to:
  = @project.visible_to
%p
  %b Ancestry:
  = @project.ancestry

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path