config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :players do
        resources :aktions, only: [:index, :show]        
      end
    end
  end

  resources :friendships
  resources :accepted_challenges
  resources :challenges
  resources :interruptions
  resources :insights
  resources :aktions do
    collection { get :continue, :start, :test, :current }
  end
  resources :role_assignments
  resources :project_memberships
  resources :team_memberships do
    member { get :update_from_api }
  end
  resources :locations, :verbs
  resources :players do
    resources :aktions
  end
  resources :teams do
    member { get :join, :leave }
    resources :projects
    resources :roles
  end

  resources :roles
  resources :projects

  root to: 'visitors#welcome'
  get '/contact' => 'visitors#contact'
  get '/welcome' => 'visitors#welcome'
  get '/help' => 'visitors#help'
  get '/chat' => 'visitors#chat'
  get '/sounds' => 'visitors#sounds'
  get '/scores' => 'visitors#scores'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/player.rb
class Player < ActiveRecord::Base
  def self.serialize(attr_name, class_name = Object, exposed_fields = [])
    super(attr_name, class_name)
    serialized_attr_accessor attr_name, exposed_fields
  end

  def self.serialized_attr_accessor(attr_name, *args)
    args.first.each do |method_name|
      eval "
        def #{method_name}
          (self[:#{attr_name}] || {})[:#{method_name}]
        end
        def #{method_name}=(value)
          self[:#{attr_name}] ||= {}
          self[:#{attr_name}][:#{method_name}] = value
        end
      "
    end
  end

  serialize :preferences, Hash, %w(current_team_id sound_choice ticking_volume warning_volume
    review_before_relax commit_length show_insights show_sidebars show_rubric)

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  after_save :init

  default_scope -> { order(:name) }

  has_many :aktions  
  has_many :teams_created, foreign_key: :creator_id
  has_many :team_memberships
  has_many :teams, through: :team_memberships
  has_many :project_memberships
  has_many :projects, through: :project_memberships
  has_many :role_assignments
  has_many :roles, through: :role_assignments
  belongs_to :first_team
  has_many :insights
  has_many :accepted_challenges
  has_many :challenges, through: :accepted_challenges

  def committed_to(proj)
    true
  end

  def current_action
    a = Aktion.find_by(player_id: id, timeslot: Aktion.current_timeslot)
    a.try(:id)
  end

  def self.time_data_hash
    {
      "data-current_action" => in_action ? 'true' : 'false'
    }
  end

  def my_teams(excluded=nil)
    teams.sort_by{ |t| -actions_for_team(t).count } - [excluded]
  end

  def actions_for_team(tm)
    Aktion.where(team_id: tm.id, player_id: id)
  end

  def actions_for_role(roll_id)
    Aktion.where(role_id: roll_id, player_id: id)
  end

  def actions_for_project(proj_id)
    Aktion.where(project_id: proj_id, player_id: id)
  end

  def actions_for_verb(vb_id)
    Aktion.where(verb_id: vb_id, player_id: id)
  end

  def today
    "Today: " +
    "#{todays_actions.map{|a|a.score}.sum} Action Points " # +
 #    "#{todays_breaths} Breaths, " +
 #    "#{todays_pushups} Pushups"
  end

  def actions
    aktions
  end

  def persist_sound_choice(sound)
    new_ticking_volume = (sound == 'ticking' ? 30 : 0)
    update_attributes(sound_choice: sound, ticking_volume: new_ticking_volume)
  end

  def frequent_actions_with_counts
    hash = aktions.by_timeslot.group_by{ |a| a.summary_hash }
    results = {}
    hash.each{ |k, v| results[v.first] = v.count }
    results.sort_by{ |r| -r[1] }
    @frequent_actions_with_counts ||= results
    # recents.sort_by{ |a| [a.team.try(:short) || 'None', a.role.try(:name) || 'None', a.verb.try(:name) || 'None'] }
  end

  def todays_actions(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    aktions.select{ |a| a.persisted? && a.timeslot.in_time_zone(self.current_time_zone).to_date == date }
  end

  def todays_points(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    todays_actions(date).map{ |a| a.score }.sum
  end

  def actions_count_before_2am_4am_6am(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    starting = date.at_beginning_of_day
    (0..2).each.map do |idx|
      ending = starting + 2.hours + idx.hours
      puts "Search between starting=#{starting} and ending=#{ending}..."
      aktions.select{ |a| a.persisted? && a.timeslot >= starting && a.timeslot <= ending }.count
    end
  end

  def actions_in_date_range(starting_on, ending_on)
    aktions.select{ |a| a.persisted? && a.in_date_range(starting_on, ending_on) }
  end

  def initials
    return nil if !name
    name.split(' ').map{|w| w[0].upcase}.join
  end

  def self.todays_grid(tz, date=nil)
    date ||= Time.zone.now.in_time_zone(tz).to_date
    midnight = date.at_beginning_of_day
    (0..47).map{ |ts| midnight + (ts*30).minutes }
  end

  def todays_grid_plus(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    midnight = date.at_beginning_of_day
    (0..47).map do |ts|
      slot = midnight + (ts*30).minutes
      [slot, Aktion.get(self, slot)]
    end
  end

  def todays_actions_from_grid(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    todays_grid_plus(date).map{ |g| g[1] }.compact
  end

  def actions_before_6am(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    starting = date.at_beginning_of_day
    ending = starting + 6.hours
    aktions.select{ |a| a.persisted? && a.timeslot >= starting && a.timeslot <= ending }
  end

  def actions_before_2am_4am_6am(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    [
      todays_grid_plus(date)[0..5].map{ |g| g[1] },
      todays_grid_plus(date)[6..11].map{ |g| g[1] },
      todays_grid_plus(date)[12..17].map{ |g| g[1] }
    ]
  end

  def actions_count_before_2am_4am_6am(date=nil)
    date ||= Time.zone.now.in_time_zone(current_time_zone).to_date
    [
      todays_grid_plus(date)[0..5].map{ |g| g[1] }.compact.count,
      todays_grid_plus(date)[6..11].map{ |g| g[1] }.compact.count,
      todays_grid_plus(date)[12..17].map{ |g| g[1] }.compact.count
    ]
  end

  def self.weekly_grid(date=nil)
    date ||= Time.zone.now.to_date
    start = date.at_beginning_of_week.to_date
    (0..6).map{ |d| start + d.days }
  end

  def self.monthly_grid(date=nil)
    date ||= Time.zone.now.to_date
    start = date.at_beginning_of_month.to_date
    x = Time.days_in_month(Time.zone.now.month)
    (0..x).map{ |d| start + d.days }
  end

  def todays_breaths
    todays_actions.map{ |a| a.breaths.to_i}.compact.sum
  end

  def todays_calisthenics
    todays_actions.map{ |a| a.pushups.to_i}.compact.sum +
    todays_actions.map{ |a| a.situps.to_i}.compact.sum +
    todays_actions.map{ |a| a.jumpjacks.to_i}.compact.sum +
    todays_actions.map{ |a| a.chairdips.to_i}.compact.sum +
    todays_actions.map{ |a| a.wallsits.to_i}.compact.sum
  end

  def todays_pushups
    todays_actions.map{ |a| a.pushups.to_i}.compact.sum
  end

  def active_roles(team=nil)
    return roles if team == nil
    roles.to_set.intersection(team.roles.to_set) rescue []
  end

  def has_role(role)
    roles.include?(role)
  end

  def committed_to(project)
    projects.include?(project)
  end

  def admin?
    role == 'admin'
  end

  def first_name
    return '' if !name
    name.split(' ').first rescue ''
  end

  def gravatar(size = 24)
    gravatar_id = Digest::MD5.hexdigest(email.downcase) unless email.blank?
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=monsterid"
  end

  def init
    team = Team.initialize_for(self)
    Role.initialize_for(team, self)
    Project.initialize_for(team, self)
  end

  def review_first
    true  #TODO: implement option
  end

  def set_default_role
    if Player.count == 0
      self.role ||= :admin
    else
      self.role ||= :user
    end
  end

  def self.sound_choices(current=nil)
    all = ['music', 'ticking', 'nature', 'silence']
    return all if !current
    all - [current.downcase]
  end

  def self.create_with_omniauth(auth)
    create! do |player|
      player.provider = auth['provider']
      player.uid = auth['uid']
      if auth['info']
        player.name = auth['info']['name'] || ""
        player.email = auth['info']['email'] || ""
      end
    end
  end

  def itemized_challenges
    return {} if !accepted_challenges.active
    accepted_challenges.active.group_by(&:item_type)
  end

  def self.active_today
    Player.all.select{|p| p.last_active.to_date == Time.zone.now.in_time_zone(p.current_time_zone).to_date }
  end

  def last_active
    last_action = aktions.sort_by{|a| a.timeslot}.last
    last_action.try(:timeslot) || created_at
  end

end

app/controllers/api/v1/players_controller.rb
class Api::V1::PlayersController < Api::V1::BaseController
  def index
    players = Player.order(:id)

    render(json: players)
  end

  def show
    player = Player.find(params[:id])

    render(json: player)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_player!, except: [:index]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show
  end

  def edit
    @player.warning_volume ||= 70
    @player.ticking_volume ||= 10
    @player.review_first
    @player.commit_length ||= 3
  end

  def update
    respond_to do |format|
      if @player.update(player_params)
        session[:sound_choice] = @player.sound_choice
        format.html { redirect_to back_or(edit_player_path(@player)), notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :role, :email, :current_time_zone, :email, :fictional,
        :current_team_id, :sound_choice, :ticking_volume, :warning_volume, :first_team_id, 
        :review_before_relax, :commit_length, :show_insights, :show_sidebars, :show_rubric, :dancing, :soccer)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= simple_form_for(@player) do |f|
  = f.error_notification

  .form-inputs
    .large-4.medium-6.small-12.columns= f.input :name
    .large-4.medium-6.small-12.columns= f.input :email
    .large-4.medium-6.small-12.columns= f.input :current_time_zone
    .large-4.medium-6.small-12.columns= f.input :sound_choice, collection: Player.sound_choices
    .large-4.medium-6.small-12.columns= f.input :ticking_volume, collection: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    .large-4.medium-6.small-12.columns= f.input :warning_volume, collection: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    - if current_player.admin?
      .large-4.medium-6.small-12.columns
        = f.input :role, collection: Player.roles.keys.map {|role| [role.titleize,role]}, label: 'TAG.com role'
        = f.input :fictional
      .large-4.medium-6.small-12.columns= f.input :review_before_relax, as: :select, collection: [['REVIEW before RELAX', true], ['RELAX before REVIEW', false]], label: 'End of Action Order', selected: @player.review_before_relax || false
      .large-4.medium-6.small-12.columns= f.input :commit_length, collection: [['1 minute', 1], ['2 minutes', 2], ['3 minutes', 3], ['4 minutes', 4], ['5 minutes', 5]], label: 'COMMIT length'
    .large-4.medium-6.small-12.columns
      = f.input :show_insights, as: :boolean
      = f.input :show_sidebars, as: :boolean
    .large-4.medium-6.small-12.columns
      = f.input :show_rubric, collection: [['None', 0], ['Simple', 1], ['Full', 2]]
    %hr

  .form-actions
    = f.button :submit

app/views/players/_player.html.haml
%tr
  %td= image_tag player.gravatar
  %td= link_to player.name, player
  %td= link_to player.aktions.count, player_aktions_path(player)
  %td= link_to player.teams.count, teams_path
  %td= link_to player.roles.count, roles_path
  %td= link_to player.projects.count, projects_path
  %td= player.created_at
  %td= current_player && current_player.admin? || current_player == player ? player.email : '(e-mail hidden)'
  %td= link_to 'Show', player
  %td= link_to 'Edit', edit_player_path(player)
  %td= link_to 'Destroy', player, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/players/edit.html.haml
- if @player = current_player
  %h2 Account Settings
- else
  %h2 Editing Player Account

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
%h1= "Listing #{I18n.t :Players}"

%table#players-table.compact
  %thead
    %tr
      %th
      %th Name
      %th Actions
      %th Teams
      %th Roles
      %th Projects
      %th Joined
      %th Email
      %th
      %th
      %th

  %tbody
    = render @players

app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

app/views/players/show.html.haml
%h3
  = @player.name
  = link_to '(Edit)', edit_player_path(@player)

%p
  %b Current time zone:
  = @player.current_time_zone
%hr

- if @player.teams
  - @player.teams.each do |team|
    %h4= team.name
    = render '/roles/roles', roles: team.roles, team: team
    .clear-both
    = render '/projects/projects', projects: team.projects, team: team
    %hr