config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :players do
        resources :aktions, only: [:index, :show]        
      end
    end
  end

  resources :friendships
  resources :accepted_challenges
  resources :challenges
  resources :interruptions
  resources :insights
  resources :aktions do
    collection { get :continue, :start, :test, :current }
  end
  resources :role_assignments
  resources :project_memberships
  resources :team_memberships do
    member { get :update_from_api }
  end
  resources :locations, :verbs
  resources :players do
    resources :aktions
  end
  resources :teams do
    member { get :join, :leave }
    resources :projects
    resources :roles
  end

  resources :roles
  resources :projects

  root to: 'visitors#welcome'
  get '/contact' => 'visitors#contact'
  get '/welcome' => 'visitors#welcome'
  get '/help' => 'visitors#help'
  get '/chat' => 'visitors#chat'
  get '/sounds' => 'visitors#sounds'
  get '/scores' => 'visitors#scores'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :team
  belongs_to :parent, class_name: 'Role'
  has_many :children, class_name: 'Role', foreign_key: 'parent_id'
  has_many :aktions
  has_many :role_assignments
  has_many :players, through: :role_assignments

  validates :team_id, presence: true

  def last_energized
    last_action_started || updated_at
  end

  def last_action_started
    aktions.map(&:timeslot).max
  end

  def self.initialize_for(solo_team, playa)
    return 'Roles already initialized' if playa.roles.first
    new_roles = [
      solo_team.roles.create!(name: 'Fearless Leader', description: 'Chooses vision and strategy, does everything else that another role has not yet been created for'),
      solo_team.roles.create!(name: 'Director of Finance', description: 'Budgets, pays the bills'),
      solo_team.roles.create!(name: 'Executive Assistant', description: 'Triages e-mail, schedules events, maintains everything'),
      solo_team.roles.create!(name: 'Lifelong Student', description: 'Explores and learns new things'),
      solo_team.roles.create!(name: 'Court Jester', description: 'Helps everyone to enjoy life more'),
    ]
    playa.roles = new_roles
  end

  def short_safe
    short || name
  end
  
  def team_role
    "#{team.name}: #{name}"
  end

  def short_team_role
    "#{team.short_safe}/#{name}"
  end

  def name_with_parent
    parent_id ? "#{parent.name_with_parent}/#{name}" : name
  end

  def name_with_short_parent
    parent_id ? "#{parent.short_name_with_short_parent}/#{name}" : name
  end

  def short_name_with_short_parent
    parent_id ? "#{parent.short_name_with_short_parent}/#{short}" : short
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_action :set_team, except: [:show, :edit, :update, :destroy]

  def index
    @roles = params[:team_id] ? Team.find_by_id(params[:team_id]).roles : current_player.roles
  end

  def show
  end

  def new
    @role = Role.new
  end

  def edit
  end

  def create
    @role = Role.new(role_params)
    if @role.short.nil? || @role.short == ''
      @role.short = @role.name
    end

    @role.team_id = params[:team_id] unless @role.team_id

    if @role.save
      RoleAssignment.create!(role_id: @role.id, player_id: current_player.id)
      render json: @role
    else
      render json: @role.errors, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to roles_path, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def set_team
      @team = Team.find_by_id(params[:team_id])
    end

    def role_params
      params.require(:role).permit(:name, :team_id, :url, :description, :parent_id, :short, :external_id)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= simple_form_for @role do |f|
  = f.error_notification

  .form-inputs
    .large-6.medium-12.columns
      .large-4.medium-4.small-4.columns= f.input :name
      .large-4.medium-4.small-4.columns= f.input :short
      .large-4.medium-4.small-4.columns= f.input :external_id
      .large-6.medium-6.small-6.columns= f.association :team, collection: current_player.teams, include_blank: true, selected: @team.try(:id), label: false, prompt: 'Team'
      - potential_parents = @team ? current_player.active_roles(@team) - [@role] - @role.children : current_player.roles
      .large-6.medium-6.small-6.columns= f.association :parent, collection: potential_parents, label: false, prompt: 'Parent Role?'
    .large-6.medium-12.columns
      .large-12= f.input :description
      .large-12= f.input :url
    %hr
  .form-actions
    = f.button :submit

app/views/roles/_role.html.haml
%tr
  - if current_player.has_role(role)
    %td.blue-text FILLING
  - else
    %td.green-text= link_to 'TAKE ON', new_role_assignment_path(role_id: role.id, player_id: current_player.id)
  %td= link_to role.team.short_safe, role.team if role.team
  %td= link_to role.name_with_short_parent, role, title: role.description
  %td= link_to role.aktions.count, aktions_path(role_id: role.id)
  %td= role.last_energized
  %td= link_to 'Show', role
  %td= link_to 'Edit', edit_role_path(role)
  %td= link_to 'Destroy', role, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/roles/_roles.html.haml
%h5
  Roles
  - if team
    = link_to "(New for #{team.name})", new_team_role_path(team)
  - else
    = link_to "(New)", new_role_path

.large-12.medium-12.small-12.columns
  %table#roles-table.compact
    %thead
      %tr
        %th
        %th Tm
        %th Name
        %th Actions
        %th Last Energized
        %th
        %th
        %th

    %tbody
      = render roles, team: team

app/views/roles/edit.html.haml
%h1 Editing Role

= render 'form'

app/views/roles/index.html.haml
= render 'roles', roles: @roles, team: @team

app/views/roles/new.html.haml
%h1 New Role

= render 'form'

app/views/roles/show.html.haml
%h4= "Role: #{@role.name}"

%p
  %b Team:
  = @role.team.name
%p
  %b Fillers:
  = @role.players.map(&:name).join(', ')

%p
  %b Description/Accountabilities:
  = simple_format @role.description